# Generated by Django 4.1.6 on 2023-02-13 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctionapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='highest_bid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='item',
            name='winning_bid',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_won', to='auctionapp.bid'),
        ),
    ]
